In [22]:
from tensorflow import keras
from keras.models import Sequential
from keras.layers.core import Dense

model = Sequential()
model.add(Dense(200, activation='relu', input_dim=12))
model.add(Dense(200, activation=None))
model.add(Dense(40, activation=None))
model.add(Dense(200, activation='relu'))
model.add(Dense(200, activation='relu'))
model.add(Dense(3, activation='sigmoid'))
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_23 (Dense)            (None, 200)               2600      
                                                                 
 dense_24 (Dense)            (None, 200)               40200     
                                                                 
 dense_25 (Dense)            (None, 40)                8040      
                                                                 
 dense_26 (Dense)            (None, 200)               8200      
                                                                 
 dense_27 (Dense)            (None, 200)               40200     
                                                                 
 dense_28 (Dense)            (None, 3)                 603       
                                                                 
Total params: 99,843
Trainable params: 99,843
Non-trai

In [23]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Dropout
# 生成虚拟数据
x_train = np.random.random((1000, 12))
y_train = np.random.randint(2, size=(1000, 3))
x_test = np.random.random((100, 12))
y_test = np.random.randint(2, size=(100, 3))

print(x_train)
print(y_train)

model.fit(x_train, y_train,
          epochs=60,
          batch_size=64)
score = model.evaluate(x_test, y_test, batch_size=128)
model.save('reskin.h5')

[[0.07314064 0.0590404  0.08535374 ... 0.91001684 0.5576565  0.97261429]
 [0.21248898 0.87106991 0.13816639 ... 0.26763361 0.0801604  0.68428234]
 [0.15289663 0.18826052 0.0869926  ... 0.53577956 0.1285485  0.87976559]
 ...
 [0.11355346 0.52815302 0.75499658 ... 0.7681974  0.36772752 0.27244555]
 [0.78935942 0.49809412 0.464129   ... 0.48966759 0.84659466 0.26607029]
 [0.49426494 0.18897022 0.01156733 ... 0.99800848 0.15351664 0.07410897]]
[[0 0 0]
 [0 0 1]
 [0 0 0]
 ...
 [1 1 0]
 [0 1 1]
 [0 0 0]]
Epoch 1/60
16/16 [==============================] - 1s 2ms/step - loss: 4.8031 - accuracy: 0.3050
Epoch 2/60
16/16 [==============================] - 0s 2ms/step - loss: 64.2894 - accuracy: 0.2940
Epoch 3/60
16/16 [==============================] - 0s 2ms/step - loss: 305.1780 - accuracy: 0.3310
Epoch 4/60
16/16 [==============================] - 0s 2ms/step - loss: 885.2088 - accuracy: 0.3310
Epoch 5/60
16/16 [==============================] - 0s 2ms/step - loss: 1891.2372 - accuracy: 0.331